namespace CoreLoader
{
    public interface IKeys
    {
        string GetKeyName(uint key);

        uint Back { get; }
        uint Tab { get; }
        uint Return { get; }
        uint Shift { get; }
        uint Control { get; }
        uint Menu { get; }
        uint Pause { get; }
        uint Capital { get; }
        uint Escape { get; }
        uint Space { get; }
        uint PageUp { get; }
        uint PageDown { get; }
        uint End { get; }
        uint Home { get; }
        uint Left { get; }
        uint Up { get; }
        uint Right { get; }
        uint Down { get; }
        uint Insert { get; }
        uint Delete { get; }
        uint Help { get; }
        uint Key0 { get; }
        uint Key1 { get; }
        uint Key2 { get; }
        uint Key3 { get; }
        uint Key4 { get; }
        uint Key5 { get; }
        uint Key6 { get; }
        uint Key7 { get; }
        uint Key8 { get; }
        uint Key9 { get; }
        uint A { get; }
        uint B { get; }
        uint C { get; }
        uint D { get; }
        uint E { get; }
        uint F { get; }
        uint G { get; }
        uint H { get; }
        uint I { get; }
        uint J { get; }
        uint K { get; }
        uint L { get; }
        uint M { get; }
        uint N { get; }
        uint O { get; }
        uint P { get; }
        uint Q { get; }
        uint R { get; }
        uint S { get; }
        uint T { get; }
        uint U { get; }
        uint V { get; }
        uint W { get; }
        uint X { get; }
        uint Y { get; }
        uint Z { get; }
        uint Lwin { get; }
        uint Rwin { get; }
        uint Numpad0 { get; }
        uint Numpad1 { get; }
        uint Numpad2 { get; }
        uint Numpad3 { get; }
        uint Numpad4 { get; }
        uint Numpad5 { get; }
        uint Numpad6 { get; }
        uint Numpad7 { get; }
        uint Numpad8 { get; }
        uint Numpad9 { get; }
        uint Multiply { get; }
        uint Add { get; }
        uint Separator { get; }
        uint Subtract { get; }
        uint Decimal { get; }
        uint Divide { get; }
        uint F1 { get; }
        uint F2 { get; }
        uint F3 { get; }
        uint F4 { get; }
        uint F5 { get; }
        uint F6 { get; }
        uint F7 { get; }
        uint F8 { get; }
        uint F9 { get; }
        uint F10 { get; }
        uint F11 { get; }
        uint F12 { get; }
        uint F13 { get; }
        uint F14 { get; }
        uint F15 { get; }
        uint F16 { get; }
        uint F17 { get; }
        uint F18 { get; }
        uint F19 { get; }
        uint F20 { get; }
        uint F21 { get; }
        uint F22 { get; }
        uint F23 { get; }
        uint F24 { get; }
        uint Lshift { get; }
        uint Rshift { get; }
        uint Lcontrol { get; }
        uint Rcontrol { get; }
        uint Lmenu { get; }
        uint Rmenu { get; }
        uint OemPlus { get; }
        uint OemComma { get; }
        uint OemMinus { get; }
        uint OemPeriod { get; }
        uint Oem1 { get; }
        uint Oem2 { get; }
        uint Oem3 { get; }
        uint Oem4 { get; }
        uint Oem5 { get; }
        uint Oem6 { get; }
        uint Oem7 { get; }
        uint Oem8 { get; }
    }
}