trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '*/*.csproj'
    versioningScheme: 'byBuildNumber'
